### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by htilssu** [htilssu/TrungTamTheDucTheThao#24]
# Menu vs Avatar dropdown bị lỗi khi response về mobile
![image](https://github.com/user-attachments/assets/a20bcd32-cf78-44c1-88e1-e6ea02f578c2)
@Tuan980Blue #16

**Comment by htilssu** [comment]
# Navbar bị scroll không fixed ở top

**Comment by Tuan980Blue** [comment]
đã fix rồi nhé

**Comment by htilssu** [comment]
đẩy lên

**Comment by htilssu** [comment]
#26 Đã fix navbar đâu
![image](https://github.com/user-attachments/assets/631c7bcb-9791-4527-bf00-a8e5eeb40aab)
